name: Update credly badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "* * * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: Nagibs/badge-readme@main
        with:       
          CREDLY_USER: ahmed-nagib # optional, but default will use the same from github
